"""create_users_table

Revision ID: ffdc0a98111c
Revises:
Create Date: 2020-11-20 15:06:02.230689

"""
from alembic import op
import sqlalchemy as sa

import os
environment = os.getenv("FLASK_ENV")
SCHEMA = os.environ.get("SCHEMA")


# revision identifiers, used by Alembic.
revision = 'ffdc0a98111c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('joined_on', sa.DateTime(), nullable=False),
    sa.Column('student', sa.Boolean(), nullable=False),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.Column('profile_pic', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )

    op.create_table("bookings", 
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tourist_id', sa.Integer(), nullable=False),
    sa.Column('tour_guide_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['tourist_id'], ['users.id']),
    sa.ForeignKeyConstraint(['tour_guide_id'], ['tour_guides.id'])
    )

    op.create_table("cities", 
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city')
    )

    op.create_table("reviews", 
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('average_rating', sa.Float(), nullable=False),
    sa.Column('communication_rating', sa.Integer(), nullable=False),
    sa.Column('knowledgability_rating', sa.Integer(), nullable=False),
    sa.Column('professionalism_rating', sa.Integer(), nullable=False),
    sa.Column('review_body', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'])
    )

    op.create_table("specialties", 
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialty', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('specialty')
    )

    op.create_table("dates", 
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=250), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date'),
    )

    op.create_table("tour_guides", 
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide_id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.ForeignKeyConstraint(['guide_id'], ['users.id']),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'])
    )

    op.create_table('tour_dates',
    sa.Column('date_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False)
    )

    op.create_table('tour_specialties',
    sa.Column('specialty_id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False)
    )

    if environment == "production":
        op.execute(f"ALTER TABLE users SET SCHEMA {SCHEMA};")
    # ### end Alembic commands ###qqqqqqqqq


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('bookings')
    op.drop_table('cities')
    op.drop_table('reviews')
    op.drop_table('specialties')
    op.drop_table('dates')
    op.drop_table('tour_guides')
    op.drop_table('tour_dates')
    op.drop_table('tour_specialties')
    # ### end Alembic commands ###